### ISSUE TITLE
CUDA version only works on device 0

### ISSUE THREAD

**Issue by gdewael** [ivan-chai/torch-linear-assignment#14]
Hi! Awesome work.

I have identified an issue when using the CUDA version of the algorithm on a GPU that is not the "first" GPU on the system:

E.g:
```
import torch
from torch_linear_assignment import batch_linear_assignment
cost = torch.randn(1000, 200, 200).to("cuda:0")
assignment = batch_linear_assignment(cost)
print(assignment)
```

Works.

But:
```
import torch
from torch_linear_assignment import batch_linear_assignment
cost = torch.randn(1000, 200, 200).to("cuda:1")
assignment = batch_linear_assignment(cost)
print(assignment)
```
Will abort because of a dumped core.
I suspect there is an issue in your custom CUDA kernel where something is probably hard-coded for the first GPU, however, I have no experience with how these work, so I cannot suggest a fix.

Thanks in advance!

**Comment by ivan-chai** [comment]
Hi! Thank you for addressing this issue. Try the newest 0.0.2 version.

Let me know if you will encounter further problems.

**Comment by gdewael** [comment]
Fast service! Solved

Cheers
