### ISSUE TITLE
[Bug] cannot find -lcudart: No such file or directory

### ISSUE THREAD

**Issue by henryzhengr** [ivan-chai/torch-linear-assignment#2]
Hi @ivan-chai 

Thank you for sharing your work!

I am trying to utilize your work in my project. However, I get this erroe

`../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcudart: No such file or directory`

Do you happen to know why?

**Comment by ivan-chai** [comment]
Hi,

Thank you for the feedback!

Do you have cuda-cudart installed in your system? What kind of OS do you use?

In Ubuntu you can use the following command:
```
sudo apt-get install cuda-cudart-12-3
```
but the version must match the cuda version installed in the system.

**Comment by henryzhengr** [comment]
Thank you! I tried to use system cuda installation now it works! The previous problem occurs cuz gcc cant find the Cuda runtime from my conda environment.
