### ISSUE TITLE
Release to Pypi?

### ISSUE THREAD

**Issue by SkafteNicki** [ivan-chai/torch-linear-assignment#6]
Hi @ivan-chai 
Thanks for the great work. I would like to hear if it would be possible for you to release the code as a package to Pypi such that it can be installed using `pip install torch-linear-assignment`?
We want to use this code as a dependency in Torchmetrics (PR: https://github.com/Lightning-AI/torchmetrics/pull/2777) for a new implementation and it messes with our CI that the package currently needs to be installed from src.
Thanks!

**Comment by ivan-chai** [comment]
Hi!
I think about Pypi myself. However, It's quite difficult to build and support CUDA extensions for all PyTorch and CUDA versions as well as all GPU architectures. Do you have any reference code with the established release pipeline? May be there are some GitHub pipelines?

**Comment by Borda** [comment]
> Hi! I think about Pypi myself. However, It's quite difficult to build and support CUDA extensions for all PyTorch and CUDA versions as well as all GPU architectures. Do you have any reference code with the established release pipeline? Are there useful examples of GitHub pipelines?

You don't need to publish compiled wheels which (you are right) could be challenging, but you can just publish sdist...
We could assist you with it 🦩

**Comment by ivan-chai** [comment]
Thank you for clarifications! I will be very grateful for some handy manual, if you have one.

**Comment by Borda** [comment]
created draft #7 and seems that the package can't be easily installed on clean env. it somehow expects that `torch` was already installed...

**Comment by ivan-chai** [comment]
Yes, Torch is needed to build Torch CUDA extensions. Thus, it is a build dependency.

**Comment by ivan-chai** [comment]
I'll look at pyproject.toml specification. However, I'm not sure it is compatible with Torch extensions.

**Comment by ivan-chai** [comment]
Thank you for writing setup code! I've merged the PR and added pyproject.toml. By now the CI pipeline seems OK.

**Comment by ivan-chai** [comment]
The package was uploaded to Pypi.

**Comment by SkafteNicki** [comment]
@ivan-chai cannot find it on Pypi?
https://pypi.org/search/?q=torch-linear-assignment

**Comment by SkafteNicki** [comment]
> @ivan-chai cannot find it on Pypi?
> https://pypi.org/search/?q=torch-linear-assignment

Alrighty, now I can find a v0.0.1post1 version. I try it out in our PR to see if everything works as expected

**Comment by ivan-chai** [comment]
The post1 release didn't include '.cu' files. I fixed this issue in the post2 release.
